export var datas = [
    {
        id: '2NA2025400090',
        name: '星际熊IP联名T恤',
        color: '黑色',
        nowprice: 199,
        reprice: 399,
        coverpic: '../img/item1c.jpg',
        itempic: '../img/item1.jpg',
        littlepic: ['../img/sitem11.jpg', '../img/sitem12.jpg', '../img/sitem13.jpg', '../img/sitem14.jpg', '../img/sitem15.jpg', '../img/sitem16.jpg'],
        bigpic: ['../img/bitem11.jpg', '../img/bitem12.jpg', '../img/bitem13.jpg', '../img/bitem14.jpg', '../img/bitem15.jpg', '../img/bitem16.jpg'],
        sizes: ['-XS', 'S', 'M', 'L', 'XL'],
        design: '星际熊IP联名款/BF风宽松廓形/涂鸦印花个性张扬',
        content: '面料:棉80.9% 聚酯纤维19.1%(绣花线除外)',
        update: '2021-06-18',
        len: '中长',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫'],
        allcolors: [['黑色', '../img/citem11.jpg']]
    },
    {
        id: '2NN3033450010',
        name: '史迪奇短袖针织衫',
        color: '米白',
        nowprice: 199,
        reprice: 499,
        coverpic: '../img/item2c.jpg',
        itempic: '../img/item2.jpg',
        littlepic: ['../img/sitem21.jpg', '../img/sitem22.jpg', '../img/sitem23.jpg', '../img/sitem24.jpg', '../img/sitem25.jpg', '../img/sitem26.jpg'],
        bigpic: ['../img/bitem21.jpg', '../img/bitem22.jpg', '../img/bitem23.jpg', '../img/bitem24.jpg', '../img/bitem25.jpg', '../img/bitem26.jpg'],
        sizes: ['S', 'M', 'L'],
        design: '烫钻史迪奇萌趣抢镜/复古少女泡泡袖型/宽松轮廓包容身材',
        content: '纱线:粘纤63.1% 锦纶34.4% 氨纶2.5%',
        update: '2021-06-23',
        len: '适中',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫'],
        allcolors: [['黑色', '../img/citem21.jpg'], ['米白', '../img/citem22.jpg'], ['绿色', '../img/citem23.jpg']]
    },
    {
        id: '2NN3020090010',
        name: '史迪奇蝴蝶结T恤',
        color: '米白',
        nowprice: 199,
        reprice: 399,
        coverpic: '../img/item3c.jpg',
        itempic: '../img/item3.jpg',
        littlepic: ['../img/sitem31.jpg', '../img/sitem32.jpg', '../img/sitem33.jpg', '../img/sitem34.jpg', '../img/sitem35.jpg', '../img/sitem36.jpg'],
        bigpic: ['../img/bitem31.jpg', '../img/bitem32.jpg', '../img/bitem33.jpg', '../img/bitem34.jpg', '../img/bitem35.jpg', '../img/bitem36.jpg'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        design: '烫钻工艺萌趣史迪奇/宽松轮廓包容身材/设计感蝴蝶结装饰',
        content: '面料:棉100%(蝴蝶结除外)',
        update: '2021-06-23',
        len: '适中',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请取下装饰件后与同类颜色衣物洗涤'],
        allcolors: [['米白', '../img/citem31.jpg']]
    },
    {
        id: '2RA3082340090',
        name: '法式小雏菊连衣裙',
        color: '黑色',
        nowprice: 239,
        reprice: 599,
        coverpic: '../img/item4c.jpg',
        itempic: '../img/item4.jpg',
        littlepic: ['../img/sitem41.jpg', '../img/sitem42.jpg', '../img/sitem43.jpg', '../img/sitem44.jpg', '../img/sitem45.jpg', '../img/sitem46.jpg'],
        bigpic: ['../img/bitem41.jpg', '../img/bitem42.jpg', '../img/bitem43.jpg', '../img/bitem44.jpg', '../img/bitem45.jpg', '../img/bitem46.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '复古清新小雏菊印花/法式精致花边翻领/收窄高腰优化身材',
        content: '面料:聚酯纤维100% 里料:聚酯纤维100%',
        update: '2021-06-25',
        len: '中长',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['黑色', '../img/citem41.jpg'], ['红杏', '../img/citem42.jpg']]
    },
    {
        id: '2RA3012320873',
        name: '小雏菊泡泡袖衬衫',
        color: '红杏',
        nowprice: 135,
        reprice: 399,
        coverpic: '../img/item5c.jpg',
        itempic: '../img/item5.jpg',
        littlepic: ['../img/sitem51.jpg', '../img/sitem52.jpg', '../img/sitem53.jpg', '../img/sitem54.jpg', '../img/sitem55.jpg', '../img/sitem56.jpg'],
        bigpic: ['../img/bitem51.jpg', '../img/bitem52.jpg', '../img/bitem53.jpg', '../img/bitem54.jpg', '../img/bitem55.jpg', '../img/bitem56.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '清新复古小雏菊碎花/精致花边低V翻领/法式少女泡泡袖',
        content: '主面料:聚酯纤维100% 撞料:棉100% 领花边:[底布]聚酯纤维93.8% 氨纶6.2% [绣线]聚酯纤维100%',
        update: '2021-06-25',
        len: '适中',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['黑色', '../img/citem51.jpg'], ['红杏', '../img/citem52.jpg']]
    },
    {
        id: '2NN2062600610',
        name: '小新联名牛仔短裤',
        color: '牛仔蓝',
        nowprice: 359,
        reprice: 599,
        coverpic: '../img/item6c.jpg',
        itempic: '../img/item6.jpg',
        littlepic: ['../img/sitem61.jpg', '../img/sitem62.jpg', '../img/sitem63.jpg', '../img/sitem64.jpg', '../img/sitem65.jpg', '../img/sitem66.jpg'],
        bigpic: ['../img/bitem61.jpg', '../img/bitem62.jpg', '../img/bitem63.jpg', '../img/bitem64.jpg', '../img/bitem65.jpg', '../img/bitem66.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新童趣减龄/破洞设计率性不羁/配小腰包丰富造型',
        content: '面料:棉100%(绣花除外) 袋布:聚酯纤维69.3% 棉30.7%',
        update: '2021-04-28',
        len: '短款',
        type: '阔腿',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请取下装饰件后与同类颜色衣物洗涤'],
        allcolors: [['牛仔蓝', '../img/citem61.jpg']]
    },
    {
        id: '2RA3082340873',
        name: '法式小雏菊连衣裙',
        color: '红杏',
        nowprice: 239,
        reprice: 599,
        coverpic: '../img/item7c.jpg',
        itempic: '../img/item7.jpg',
        littlepic: ['../img/sitem71.jpg', '../img/sitem72.jpg', '../img/sitem73.jpg', '../img/sitem74.jpg', '../img/sitem75.jpg', '../img/sitem76.jpg'],
        bigpic: ['../img/bitem71.jpg', '../img/bitem72.jpg', '../img/bitem73.jpg', '../img/bitem74.jpg', '../img/bitem75.jpg', '../img/bitem76.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '复古清新小雏菊印花/法式精致花边翻领/收窄高腰优化身材',
        content: '面料:聚酯纤维100% 里料:聚酯纤维100%',
        update: '2020-06-25',
        len: '中长',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['黑色', '../img/citem71.jpg'], ['红杏', '../img/citem72.jpg']]
    },
    {
        id: '2NN2082620610',
        name: '小新牛仔背带短裤',
        color: '牛仔蓝',
        nowprice: 419,
        reprice: 699,
        coverpic: '../img/item8c.jpg',
        itempic: '../img/item8.jpg',
        littlepic: ['../img/sitem81.jpg', '../img/sitem82.jpg', '../img/sitem83.jpg', '../img/sitem84.jpg', '../img/sitem85.jpg', '../img/sitem86.jpg'],
        bigpic: ['../img/bitem81.jpg', '../img/bitem82.jpg', '../img/bitem83.jpg', '../img/bitem84.jpg', '../img/bitem85.jpg', '../img/bitem86.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新联名系列/青春减龄背带裤型/丹宁回潮连体设计',
        content: '面料:棉100%(背带除外) 袋布:聚酯纤维69.3% 棉30.7%',
        update: '2021-04-28',
        len: '短款',
        type: '阔腿',
        washways: ['请取下装饰件后与同类颜色衣物洗涤'],
        allcolors: [['牛仔蓝', '../img/citem81.jpg']]
    },
    {
        id: '2RA3012320090',
        name: '小雏菊泡泡袖衬衫',
        color: '黑色',
        nowprice: 135,
        reprice: 339,
        coverpic: '../img/item9c.jpg',
        itempic: '../img/item9.jpg',
        littlepic: ['../img/sitem91.jpg', '../img/sitem92.jpg', '../img/sitem93.jpg', '../img/sitem94.jpg', '../img/sitem95.jpg', '../img/sitem96.jpg'],
        bigpic: ['../img/bitem91.jpg', '../img/bitem92.jpg', '../img/bitem93.jpg', '../img/bitem94.jpg', '../img/bitem95.jpg', '../img/bitem96.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '清新复古小雏菊碎花/精致花边低V翻领/法式少女泡泡袖',
        content: '主面料:聚酯纤维100% 撞料:棉100% 领花边:[底布]聚酯纤维93.8% 氨纶6.2% [绣线]聚酯纤维100%',
        update: '2020-06-25',
        len: '适中',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['黑色', '../img/citem91.jpg'], ['红杏', '../img/citem92.jpg']]
    },
    {
        id: '2NN2080460030',
        name: '小新联名连体短裤',
        color: '灰色',
        nowprice: 629,
        reprice: 899,
        coverpic: '../img/item10c.jpg',
        itempic: '../img/item10.jpg',
        littlepic: ['../img/sitem101.jpg', '../img/sitem102.jpg', '../img/sitem103.jpg', '../img/sitem104.jpg', '../img/sitem105.jpg', '../img/sitem106.jpg'],
        bigpic: ['../img/bitem101.jpg', '../img/bitem102.jpg', '../img/bitem103.jpg', '../img/bitem104.jpg', '../img/bitem105.jpg', '../img/bitem106.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新联名系列/甜酷工装连体设计/刺绣标语个性态度',
        content: '面料:聚酯纤维83.5% 粘纤14.5% 氨纶2.0%(绣花线除外) 里料:聚酯纤维100%',
        update: '2021-04-28',
        len: '短款',
        type: '阔腿',
        washways: ['请扣合好后与同类颜色衣物洗涤', '请取下腰带后洗涤'],
        allcolors: [['灰色', '../img/citem101.jpg']]
    },
    {
        id: '2NN2062610030',
        name: '小新联名阔腿短裤',
        color: '灰色',
        nowprice: 299,
        reprice: 499,
        coverpic: '../img/item11c.jpg',
        itempic: '../img/item11.jpg',
        littlepic: ['../img/sitem111.jpg', '../img/sitem112.jpg', '../img/sitem113.jpg', '../img/sitem114.jpg', '../img/sitem115.jpg', '../img/sitem116.jpg'],
        bigpic: ['../img/bitem111.jpg', '../img/bitem112.jpg', '../img/bitem113.jpg', '../img/bitem114.jpg', '../img/bitem115.jpg', '../img/bitem116.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新联名款/A字轮廓宽松裤筒/带扣兔公仔童趣可爱',
        content: '面料:聚酯纤维83.5% 粘纤14.5% 氨纶2.0% 里料:聚酯纤维100% 袋布:聚酯纤维100%',
        update: '2021-04-28',
        len: '短款',
        type: '阔腿',
        washways: ['请扣合好后与同类颜色衣物洗涤', '洗涤前请取下装饰件'],
        allcolors: [['灰色', '../img/citem111.jpg']]
    },
    {
        id: '2NN3080220600',
        name: '泡泡袖牛仔连衣裙',
        color: '蓝色',
        nowprice: 399,
        reprice: 999,
        coverpic: '../img/item12c.jpg',
        itempic: '../img/item12.jpg',
        littlepic: ['../img/sitem121.jpg', '../img/sitem122.jpg', '../img/sitem123.jpg', '../img/sitem124.jpg', '../img/sitem125.jpg', '../img/sitem126.jpg'],
        bigpic: ['../img/bitem121.jpg', '../img/bitem122.jpg', '../img/bitem123.jpg', '../img/bitem124.jpg', '../img/bitem125.jpg', '../img/bitem126.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '童趣治愈感史迪奇/复古丹宁甜酷率性/少女减龄泡泡袖',
        content: '面料:棉91.0% 聚酯纤维8.5% 氨纶0.5%(绣花线除外)',
        update: '2021-06-23',
        len: '5-6分长',
        type: '合体',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['蓝色', '../img/citem121.jpg']]
    },
    {
        id: '2NN2062640610',
        name: '刺绣小新牛仔长裤',
        color: '牛仔蓝',
        nowprice: 359,
        reprice: 599,
        coverpic: '../img/item13c.jpg',
        itempic: '../img/item13.jpg',
        littlepic: ['../img/sitem131.jpg', '../img/sitem132.jpg', '../img/sitem133.jpg', '../img/sitem134.jpg', '../img/sitem135.jpg', '../img/sitem136.jpg'],
        bigpic: ['../img/bitem131.jpg', '../img/bitem132.jpg', '../img/bitem133.jpg', '../img/bitem134.jpg', '../img/bitem135.jpg', '../img/bitem136.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新联名系列/锥形轮廓修身显瘦/破洞设计个性不羁',
        content: '面料:棉100%(绣花线除外)',
        update: '2021-04-29',
        len: '9分-长款',
        type: '阔腿',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['牛仔蓝', '../img/citem131.jpg']]
    },
    {
        id: '2NN2012690410',
        name: '小新字母短袖衬衫',
        color: '黄色',
        nowprice: 299,
        reprice: 599,
        coverpic: '../img/item14c.jpg',
        itempic: '../img/item14.jpg',
        littlepic: ['../img/sitem141.jpg', '../img/sitem142.jpg', '../img/sitem143.jpg', '../img/sitem144.jpg', '../img/sitem145.jpg', '../img/sitem146.jpg'],
        bigpic: ['../img/bitem141.jpg', '../img/bitem142.jpg', '../img/bitem143.jpg', '../img/bitem144.jpg', '../img/bitem145.jpg', '../img/bitem146.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新联名系列/醒目标语个性活力/公仔装饰宽大版型',
        content: '面料:棉100%',
        update: '2021-04-28',
        len: '中长',
        type: '宽松',
        washways: ['中温熨烫', '请扣合好后与同类颜色衣物洗涤', '洗涤前请取下装饰件'],
        allcolors: [['黄色', '../img/citem141.jpg']]
    },
    {
        id: '2NN2072590610',
        name: '小新图案牛仔半裙',
        color: '牛仔蓝',
        nowprice: 249,
        reprice: 499,
        coverpic: '../img/item15c.jpg',
        itempic: '../img/item15.jpg',
        littlepic: ['../img/sitem151.jpg', '../img/sitem152.jpg', '../img/sitem153.jpg', '../img/sitem154.jpg', '../img/sitem155.jpg', '../img/sitem156.jpg'],
        bigpic: ['../img/bitem151.jpg', '../img/bitem152.jpg', '../img/bitem153.jpg', '../img/bitem154.jpg', '../img/bitem155.jpg', '../img/bitem156.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新联名系列/丹宁裙装甜酷率性/洗水做旧复古加持',
        content: '面料:棉100%(绣花线除外) 袋布:聚酯纤维69.3% 棉30.7%',
        update: '2021-04-28',
        len: '5-6分长',
        type: '合体',
        washways: ['请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['牛仔蓝', '../img/citem151.jpg']]
    },
    {
        id: '2NA2070020610',
        name: '小新刺绣牛仔短裙',
        color: '牛仔蓝',
        nowprice: 299,
        reprice: 599,
        coverpic: '../img/item16c.jpg',
        itempic: '../img/item16.jpg',
        littlepic: ['../img/sitem161.jpg', '../img/sitem162.jpg', '../img/sitem163.jpg', '../img/sitem164.jpg', '../img/sitem165.jpg', '../img/sitem166.jpg'],
        bigpic: ['../img/bitem161.jpg', '../img/bitem162.jpg', '../img/bitem163.jpg', '../img/bitem164.jpg', '../img/bitem165.jpg', '../img/bitem166.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '刺绣小新童趣抢镜/丹宁回潮A字裙型/高腰剪裁凸显大长腿',
        content: '面料:棉100% 绣花线:聚酯纤维100% 袋布:聚酯纤维82.3% 棉17.7%',
        update: '2021-04-28',
        len: '5-6分长',
        type: '合体',
        washways: ['请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['牛仔蓝', '../img/citem161.jpg']]
    },
    {
        id: '2NN2012680010',
        name: '小新图案方领衬衫',
        color: '米白',
        nowprice: 199,
        reprice: 399,
        coverpic: '../img/item17c.jpg',
        itempic: '../img/item17.jpg',
        littlepic: ['../img/sitem171.jpg', '../img/sitem172.jpg', '../img/sitem173.jpg', '../img/sitem174.jpg', '../img/sitem175.jpg', '../img/sitem176.jpg'],
        bigpic: ['../img/bitem171.jpg', '../img/bitem172.jpg', '../img/bitem173.jpg', '../img/bitem174.jpg', '../img/bitem175.jpg', '../img/bitem176.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: 'IP联名款系列/童趣可爱小新复古波点/甜酷短款法式方领',
        content: '面料:棉97.8% 氨纶2.2%',
        update: '2021-04-28',
        len: '短款',
        type: '合体',
        washways: ['请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['米白', '../img/citem171.jpg'], ['黑色', '../img/citem172.jpg']]
    },
    {
        id: '2NN2032560462',
        name: '小新图案针织上衣',
        color: '姜黄',
        nowprice: 299,
        reprice: 499,
        coverpic: '../img/item18c.jpg',
        itempic: '../img/item18.jpg',
        littlepic: ['../img/sitem181.jpg', '../img/sitem182.jpg', '../img/sitem183.jpg', '../img/sitem184.jpg', '../img/sitem185.jpg', '../img/sitem186.jpg'],
        bigpic: ['../img/bitem181.jpg', '../img/bitem182.jpg', '../img/bitem183.jpg', '../img/bitem184.jpg', '../img/bitem185.jpg', '../img/bitem186.jpg'],
        sizes: ['S', 'M', 'L'],
        design: 'IP联名款系列/童真可爱蜡笔小新/少女感减龄大翻领',
        content: '衫身:粘纤80.1% 锦纶19.9% 罗纹:粘纤65.4% 锦纶34.6% 领子:粘纤79.5% 锦纶20.5%',
        update: '2021-04-28',
        len: '适中',
        type: '宽松',
        washways: [],
        allcolors: [['姜黄', '../img/citem181.jpg']]
    },
    {
        id: '2NN2072700410',
        name: '小新标语高腰短裙',
        color: '黄色',
        nowprice: 419,
        reprice: 599,
        coverpic: '../img/item19c.jpg',
        itempic: '../img/item19.jpg',
        littlepic: ['../img/sitem191.jpg', '../img/sitem192.jpg', '../img/sitem193.jpg', '../img/sitem194.jpg', '../img/sitem195.jpg', '../img/sitem196.jpg'],
        bigpic: ['../img/bitem191.jpg', '../img/bitem192.jpg', '../img/bitem193.jpg', '../img/bitem194.jpg', '../img/bitem195.jpg', '../img/bitem196.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新联名系列/标语图案个性态度/圆形腰包时髦加分',
        content: '面料:棉100% 里料:聚酯纤维100%',
        update: '2021-04-28',
        len: '短款',
        type: '合体',
        washways: ['请取下装饰件后与同类颜色衣物洗涤'],
        allcolors: [['黄色', '../img/citem191.jpg']]
    },
    {
        id: '2NN2082480010',
        name: '蜡笔小新连衣裙',
        color: '米白',
        nowprice: 489,
        reprice: 699,
        coverpic: '../img/item20c.jpg',
        itempic: '../img/item20.jpg',
        littlepic: ['../img/sitem201.jpg', '../img/sitem202.jpg', '../img/sitem203.jpg', '../img/sitem204.jpg', '../img/sitem205.jpg', '../img/sitem206.jpg'],
        bigpic: ['../img/bitem201.jpg', '../img/bitem202.jpg', '../img/bitem203.jpg', '../img/bitem204.jpg', '../img/bitem205.jpg', '../img/bitem206.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '童趣搞怪蜡笔小新/休闲活力T恤裙款/配公仔包可爱减龄',
        content: '面料:粘纤53.3% 锦纶40.8% 氨纶5.9%(绣花线除外) 网里:聚酯纤维100%',
        update: '2021-04-28',
        len: '5-6分长',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请将装饰件取下后分开洗涤'],
        allcolors: [['米白', '../img/citem201.jpg'], ['黑色', '../img/citem202.jpg']]
    },
    {
        id: '2NN2022490090',
        name: '小新图案中长T恤',
        color: '黑色',
        nowprice: 349,
        reprice: 499,
        coverpic: '../img/item21c.jpg',
        itempic: '../img/item21.jpg',
        littlepic: ['../img/sitem211.jpg', '../img/sitem212.jpg', '../img/sitem213.jpg', '../img/sitem214.jpg', '../img/sitem215.jpg', '../img/sitem216.jpg'],
        bigpic: ['../img/bitem211.jpg', '../img/bitem212.jpg', '../img/bitem213.jpg', '../img/bitem214.jpg', '../img/bitem215.jpg', '../img/bitem216.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新联名系列/童趣搞怪小新图案/宽大轮廓公仔装饰',
        content: '面料:棉100%(绣花/公仔别针除外)',
        update: '2021-04-28',
        len: '中长',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '洗涤前请取下装饰件'],
        allcolors: [['米白', '../img/citem211.jpg'], ['黑色', '../img/citem212.jpg'], ['浅紫', '../img/citem213.jpg']]
    },
    {
        id: '2NN3070190610',
        name: '烫钻史迪奇牛仔裙',
        color: '牛仔蓝',
        nowprice: 349,
        reprice: 499,
        coverpic: '../img/item22c.jpg',
        itempic: '../img/item22.jpg',
        littlepic: ['../img/sitem221.jpg', '../img/sitem222.jpg', '../img/sitem223.jpg', '../img/sitem224.jpg', '../img/sitem225.jpg', '../img/sitem226.jpg'],
        bigpic: ['../img/bitem221.jpg', '../img/bitem222.jpg', '../img/bitem223.jpg', '../img/bitem224.jpg', '../img/bitem225.jpg', '../img/bitem226.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '烫钻史迪奇童趣减龄/丹宁裙款甜酷加持/金属排扣高腰收腹',
        content: '面料:棉100%(含微量其他纤维) 袋布:聚酯纤维82.6% 棉17.4%',
        update: '2021-06-23',
        len: '5-6分长',
        type: '合体',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['牛仔蓝', '../img/citem221.jpg']]
    },
    {
        id: '2NN2022530480',
        name: '小新图案落肩T恤',
        color: '浅黄',
        nowprice: 203,
        reprice: 339,
        coverpic: '../img/item23c.jpg',
        itempic: '../img/item23.jpg',
        littlepic: ['../img/sitem231.jpg', '../img/sitem232.jpg', '../img/sitem233.jpg', '../img/sitem234.jpg', '../img/sitem235.jpg', '../img/sitem236.jpg'],
        bigpic: ['../img/bitem231.jpg', '../img/bitem232.jpg', '../img/bitem233.jpg', '../img/bitem234.jpg', '../img/bitem235.jpg', '../img/bitem236.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '童趣搞怪蜡笔小新/慵懒落肩宽松设计/甜酷短款抽绳衣摆',
        content: '面料:棉94.3% 氨纶5.7%(绣花除外)',
        update: '2021-04-28',
        len: '短款',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫'],
        allcolors: [['米白', '../img/citem231.jpg'], ['黑色', '../img/citem232.jpg'], ['浅黄', '../img/citem233.jpg']]
    },
    {
        id: '2NA2020630630',
        name: '刺绣冥想兔棉T恤',
        color: '粉蓝',
        nowprice: 199,
        reprice: 399,
        coverpic: '../img/item24c.jpg',
        itempic: '../img/item24.jpg',
        littlepic: ['../img/sitem241.jpg', '../img/sitem242.jpg', '../img/sitem243.jpg', '../img/sitem244.jpg', '../img/sitem245.jpg', '../img/sitem246.jpg'],
        bigpic: ['../img/bitem241.jpg', '../img/bitem242.jpg', '../img/bitem243.jpg', '../img/bitem244.jpg', '../img/bitem245.jpg', '../img/bitem246.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '跨界合作IP款/童趣治愈感冥想兔/重工刺绣精致立体',
        content: '面料:棉100%(绣花除外) 网里:锦纶100%',
        update: '2021-05-26',
        len: '适中',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫'],
        allcolors: [['黑色', '../img/citem241.jpg'], ['米白', '../img/citem242.jpg'], ['粉蓝', '../img/citem243.jpg']]
    },
    {
        id: '2NN3020010090',
        name: '史迪奇图案潮T恤',
        color: '黑色',
        nowprice: 279,
        reprice: 399,
        coverpic: '../img/item25c.jpg',
        itempic: '../img/item25.jpg',
        littlepic: ['../img/sitem251.jpg', '../img/sitem252.jpg', '../img/sitem253.jpg', '../img/sitem254.jpg', '../img/sitem255.jpg', '../img/sitem256.jpg'],
        bigpic: ['../img/bitem251.jpg', '../img/bitem252.jpg', '../img/bitem253.jpg', '../img/bitem254.jpg', '../img/bitem255.jpg', '../img/bitem256.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '迪士尼IP联名款/萌趣治愈感史迪奇/宽松轮廓包容身材',
        content: '面料:棉89.5% 氨纶10.5%(绣花除外)',
        update: '2021-06-23',
        len: '适中',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫'],
        allcolors: [['黑色', '../img/citem251.jpg'], ['米白', '../img/citem252.jpg'], ['粉红', '../img/citem253.jpg']]
    },
    {
        id: '2NN3010120018',
        name: '史迪奇中长款衬衫',
        color: '白色',
        nowprice: 479,
        reprice: 799,
        coverpic: '../img/item26c.jpg',
        itempic: '../img/item26.jpg',
        littlepic: ['../img/sitem261.jpg', '../img/sitem262.jpg', '../img/sitem263.jpg', '../img/sitem264.jpg', '../img/sitem265.jpg', '../img/sitem266.jpg'],
        bigpic: ['../img/bitem261.jpg', '../img/bitem262.jpg', '../img/bitem263.jpg', '../img/bitem264.jpg', '../img/bitem265.jpg', '../img/bitem266.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '迪士尼IP联名款/萌星童趣史迪奇图案/中长轮廓率性bf风',
        content: '面料:聚酯纤维56.9% 棉39.7% 氨纶3.4%',
        update: '2021-06-23',
        len: '中长',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤', '洗涤前请取下装饰件'],
        allcolors: [['白色', '../img/citem261.jpg']]
    },
    {
        id: '2NN2042720030',
        name: '小新联名西装马甲',
        color: '灰色',
        nowprice: 419,
        reprice: 699,
        coverpic: '../img/item27c.jpg',
        itempic: '../img/item27.jpg',
        littlepic: ['../img/sitem271.jpg', '../img/sitem272.jpg', '../img/sitem273.jpg', '../img/sitem274.jpg', '../img/sitem275.jpg', '../img/sitem276.jpg'],
        bigpic: ['../img/bitem271.jpg', '../img/bitem272.jpg', '../img/bitem273.jpg', '../img/bitem274.jpg', '../img/bitem275.jpg', '../img/bitem276.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新联名款/甜酷主义西装马甲/带扣兔公仔童趣可爱',
        content: '面料:聚酯纤维83.5% 粘纤14.5% 氨纶2.0% 里料:聚酯纤维100% 袋布:聚酯纤维100%',
        update: '2021-04-28',
        len: '适中',
        type: '宽松',
        washways: ['请扣合好后与同类颜色衣物洗涤', '洗涤前请取下装饰件'],
        allcolors: [['灰色', '../img/citem271.jpg']]
    },
    {
        id: '2NA2020640630',
        name: '冥想兔图案T恤',
        color: '粉蓝',
        nowprice: 199,
        reprice: 399,
        coverpic: '../img/item28c.jpg',
        itempic: '../img/item28.jpg',
        littlepic: ['../img/sitem281.jpg', '../img/sitem282.jpg', '../img/sitem283.jpg', '../img/sitem284.jpg', '../img/sitem285.jpg', '../img/sitem286.jpg'],
        bigpic: ['../img/bitem281.jpg', '../img/bitem282.jpg', '../img/bitem283.jpg', '../img/bitem284.jpg', '../img/bitem285.jpg', '../img/bitem286.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '童趣治愈感冥想兔/闪亮烫钻潮酷时髦/宽松落肩率性休闲',
        content: '面料:棉100%',
        update: '2021-05-26',
        len: '适中',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫'],
        allcolors: [['米白', '../img/citem281.jpg'], ['粉蓝', '../img/citem282.jpg'], ['粉紫', '../img/citem283.jpg']]
    },
    {
        id: '2NN3060210600',
        name: '史迪奇牛仔阔腿裤',
        color: '蓝色',
        nowprice: 299,
        reprice: 599,
        coverpic: '../img/item29c.jpg',
        itempic: '../img/item29.jpg',
        littlepic: ['../img/sitem291.jpg', '../img/sitem292.jpg', '../img/sitem293.jpg', '../img/sitem294.jpg', '../img/sitem295.jpg', '../img/sitem296.jpg'],
        bigpic: ['../img/bitem291.jpg', '../img/bitem292.jpg', '../img/bitem293.jpg', '../img/bitem294.jpg', '../img/bitem295.jpg', '../img/bitem296.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '史迪奇合作款系列/个性假腰带式设计/直筒轮廓率性休闲',
        content: '面料:棉100%',
        update: '2021-06-23',
        len: '9分-长款',
        type: '阔腿',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['黑色', '../img/citem291.jpg'], ['蓝色', '../img/citem292.jpg']]
    },
    {
        id: '2NN3080050090',
        name: '烫钻不规则连衣裙',
        color: '黑色',
        nowprice: 359,
        reprice: 599,
        coverpic: '../img/item30c.jpg',
        itempic: '../img/item30.jpg',
        littlepic: ['../img/sitem301.jpg', '../img/sitem302.jpg', '../img/sitem303.jpg', '../img/sitem304.jpg', '../img/sitem305.jpg', '../img/sitem306.jpg'],
        bigpic: ['../img/bitem301.jpg', '../img/bitem302.jpg', '../img/bitem303.jpg', '../img/bitem304.jpg', '../img/bitem305.jpg', '../img/bitem306.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '烫钻史迪奇童趣炫酷/活力休闲T恤裙款/不规则下摆设计',
        content: '面料:粘纤54.2% 锦纶40.0% 氨纶5.8%',
        update: '2021-06-23',
        len: '5-6分长',
        type: '宽松',
        washways: ['30℃以下轻柔手洗,不可机洗', '装饰工艺部位不可揉搓,不可熨烫'],
        allcolors: [['黑色', '../img/citem301.jpg'], ['米白', '../img/citem302.jpg']]
    },
    {
        id: '2NN2022500760',
        name: '刺绣小新纯棉T恤',
        color: '浅紫',
        nowprice: 279,
        reprice: 399,
        coverpic: '../img/item31c.jpg',
        itempic: '../img/item31.jpg',
        littlepic: ['../img/sitem311.jpg', '../img/sitem312.jpg', '../img/sitem313.jpg', '../img/sitem314.jpg', '../img/sitem315.jpg', '../img/sitem316.jpg'],
        bigpic: ['../img/bitem311.jpg', '../img/bitem312.jpg', '../img/bitem313.jpg', '../img/bitem314.jpg', '../img/bitem315.jpg', '../img/bitem316.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '蜡笔小新联名系列/童趣治愈感小新图案/慵懒随性落肩袖',
        content: '面料:棉100%(绣花线除外)',
        update: '2021-04-28',
        len: '适中',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫'],
        allcolors: [['米白', '../img/citem311.jpg'], ['浅紫', '../img/citem312.jpg']]
    },
    {
        id: '2NN1085250610',
        name: '爱丽丝牛仔连衣裙',
        color: '牛仔蓝',
        nowprice: 559,
        reprice: 799,
        coverpic: '../img/item32c.jpg',
        itempic: '../img/item32.jpg',
        littlepic: ['../img/sitem321.jpg', '../img/sitem322.jpg', '../img/sitem323.jpg', '../img/sitem324.jpg', '../img/sitem325.jpg', '../img/sitem326.jpg'],
        bigpic: ['../img/bitem321.jpg', '../img/bitem322.jpg', '../img/bitem323.jpg', '../img/bitem324.jpg', '../img/bitem325.jpg', '../img/bitem326.jpg'],
        sizes: ['XS', 'S', 'M', 'L', '-XL'],
        design: '迪士尼爱丽丝联名/洗水丹宁X型轮廓/刺绣图案童趣抢镜',
        content: '面料:棉90.7% 聚酯纤维8.9% 氨纶0.4%(绣花线除外)',
        update: '2021-02-18',
        len: '5-6分长',
        type: '合体',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['牛仔蓝', '../img/citem321.jpg']]
    },
    {
        id: '2NN3020020090',
        name: '史迪奇刺绣棉T恤',
        color: '黑色',
        nowprice: 419,
        reprice: 599,
        coverpic: '../img/item33c.jpg',
        itempic: '../img/item33.jpg',
        littlepic: ['../img/sitem331.jpg', '../img/sitem332.jpg', '../img/sitem333.jpg', '../img/sitem334.jpg', '../img/sitem335.jpg', '../img/sitem336.jpg'],
        bigpic: ['../img/bitem331.jpg', '../img/bitem332.jpg', '../img/bitem333.jpg', '../img/bitem334.jpg', '../img/bitem335.jpg', '../img/bitem336.jpg'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        design: '萌趣治愈感史迪奇/醒目标语个性态度/男友风格中长轮廓',
        content: '面料:棉100%(绣花除外)',
        update: '2021-06-23',
        len: '中长',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫'],
        allcolors: [['黑色', '../img/citem331.jpg'], ['粉红', '../img/citem332.jpg'], ['杏色', '../img/citem333.jpg']]
    },
    {
        id: '2NN4020200090',
        name: '星际熊宽松棉卫衣',
        color: '黑色',
        nowprice: 479,
        reprice: 599,
        coverpic: '../img/item34c.jpg',
        itempic: '../img/item34.jpg',
        littlepic: ['../img/sitem341.jpg', '../img/sitem342.jpg', '../img/sitem343.jpg', '../img/sitem344.jpg', '../img/sitem345.jpg', '../img/sitem346.jpg'],
        bigpic: ['../img/bitem341.jpg', '../img/bitem342.jpg', '../img/bitem343.jpg', '../img/bitem344.jpg', '../img/bitem345.jpg', '../img/bitem346.jpg'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        design: '童趣潮玩星际熊联名/活力休闲卫衣轮廓/慵懒随性落肩袖',
        content: '面料:棉100%(绣花章除外) 罗纹:棉75.4% 聚酯纤维22.3% 氨纶2.3%',
        update: '2021-09-22',
        len: '适中',
        type: '宽松',
        washways: ['30℃以下轻柔手洗,不可机洗', '装饰工艺部位不可揉搓,不可熨烫'],
        allcolors: [['黑色', '../img/citem341.jpg'], ['米白', '../img/citem342.jpg'], ['浅绿', '../img/citem343.jpg']]
    },
    {
        id: '2RA3082370480',
        name: '波点提花连衣裙',
        color: '浅黄',
        nowprice: 199,
        reprice: 499,
        coverpic: '../img/item35c.jpg',
        itempic: '../img/item35.jpg',
        littlepic: ['../img/sitem351.jpg', '../img/sitem352.jpg', '../img/sitem353.jpg', '../img/sitem354.jpg', '../img/sitem355.jpg', '../img/sitem356.jpg'],
        bigpic: ['../img/bitem351.jpg', '../img/bitem352.jpg', '../img/bitem353.jpg', '../img/bitem354.jpg', '../img/bitem355.jpg', '../img/bitem356.jpg'],
        sizes: ['XS', 'S', 'M', '-L', '-XL'],
        design: '波点提花精致新颖/娃娃裙型微甜减龄/碎褶裙摆飘逸灵动',
        content: '面料:聚酯纤维100% 里料:聚酯纤维100%',
        update: '2020-06-25',
        len: '中长',
        type: '宽松',
        washways: [],
        allcolors: [['浅粉', '../img/citem351.jpg'], ['浅黄', '../img/citem352.jpg']]
    },
    {
        id: '2NN2012630610',
        name: '刺绣小新牛仔外套',
        color: '牛仔蓝',
        nowprice: 489,
        reprice: 699,
        coverpic: '../img/item36c.jpg',
        itempic: '../img/item36.jpg',
        littlepic: ['../img/sitem361.jpg', '../img/sitem362.jpg', '../img/sitem363.jpg', '../img/sitem364.jpg', '../img/sitem365.jpg', '../img/sitem366.jpg'],
        bigpic: ['../img/bitem361.jpg', '../img/bitem362.jpg', '../img/bitem363.jpg', '../img/bitem364.jpg', '../img/bitem365.jpg', '../img/bitem366.jpg'],
        sizes: ['-XS', 'S', 'M', 'L', '-XL'],
        design: 'IP联名款系列/蜡笔小新刺绣抢镜/男友风格宽大轮廓',
        content: '面料:棉90.9% 聚酯纤维8.8% 氨纶0.3%(绣花除外)',
        update: '2021-04-29',
        len: '适中',
        type: '宽松',
        washways: ['装饰工艺部位不可揉搓,不可熨烫', '请扣合好后与同类颜色衣物洗涤'],
        allcolors: [['牛仔蓝', '../img/citem361.jpg']]
    }
]